{{- if .Values.replicas.autoscalingEnabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "application.fullname" . }}
  minReplicas: {{ .Values.replicas.minReplicas }}
  maxReplicas: {{ .Values.replicas.maxReplicas }}
  metrics:
    {{- if .Values.replicas.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.replicas.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.replicas.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.replicas.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
