# These fields need to be rewritten after generation
schema: draft-07
name: app-gke
description: GKE MD App
ref: github.com/massdriver-cloud/app-gke
access: private
type: application

# Note: Chart.yaml needs to be rewritten after
# generation. The CLI does this, but remember to check!
deployment:
  type: custom
  path: ./chart

params:
  properties:
    name:
      type: string
    namespace:
      type: string
      default: default
    image:
      type: object
      properties:
        repository:
          type: string
        sha:
          type: string
        tag:
          type: string
    resource_requests:
      type: object
      properties:
        cpu:
          type: string
        memory:
          type: string
    port:
      type: integer
    autoscaling:
      type: object
      properties:
        enabled:
          type: boolean
          default: false
        minReplicas:
          type: integer
          default: 1
        maxReplicas:
          type: integer
          default: 2
        targetCPUUtilizationPercentage:
          type: integer
          default: 90
    ingress:
      type: object
      properties:
        enabled:
          type: boolean
        host:
          type: string
        path:
          type: string
          default: '/'
    envs:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          value:
            type: string

# list app dependencies here
# massdriver will add environment variables and
# manage secure access to them for you
# dependencies:
#   database:
#     type: massdriver/postgresql-authentication
#     envs:
#       - name: DB_HOST
#         path: data.authentication.hostname
#     policies:
#       - read
