image:
  repository:
  tag:

command: []
args: []

envs: []

serviceAccount:
  annotations: {}
  labels: {}
  name:

resourceRequests: {}
resourceLimits: {}

job:
  schedule:
  concurrencyPolicy:
  completions:
  parallelism:

commonLabels: {}

pod:
  annotations: {}
  labels: {}