apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "scheduled-job.fullname" . }}
  labels:
    {{- include "scheduled-job.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: 1
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      completions: {{ .Values.completions }}
      parallelism: {{ .Values.parallelism }}
      template:
        metadata:
          labels:
            {{- include "scheduled-job.selectorLabels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          serviceAccountName: {{ include "scheduled-job.fullname" . }}
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            {{- with .Values.securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: Always
            {{- with .Values.command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.args }}
            args:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.envs }}
            env:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            resources:
              {{- with .Values.resourceRequests }}
              requests:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .Values.resourceLimits }}
              limits:
                {{- toYaml . | nindent 16 }}
              {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
