apiVersion: batch/v1beta1
kind: Job
metadata:
  name: {{ include "adhoc-job.timestamped-name" . }}
  labels:
    {{- include "adhoc-job.labels" . | nindent 4 }}
spec:
  completions: {{ .Values.completions }}
  parallelism: {{ .Values.parallelism }}
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "adhoc-job.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "adhoc-job.fullname" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        {{- with .Values.command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.envs }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- with .Values.resourceRequests }}
          requests:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resourceLimits }}
          limits:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
