# These fields need to be rewritten after generation
schema: draft-07
name: k8s-job
description: Massdriver K8s Job
ref: github.com/massdriver-cloud/k8s-job
access: private
type: application

params:
  properties:
    name:
      type: string
    namespace:
      type: string
      default: default
    image:
      type: object
      properties:
        repository:
          type: string
        sha:
          type: string
        tag:
          type: string
    resource_requests:
      type: object
      properties:
        cpu:
          type: string
        memory:
          type: string
    autoscaling:
      type: object
      properties:
        enabled:
          type: boolean
          default: false
        minReplicas:
          type: integer
          default: 1
        maxReplicas:
          type: integer
          default: 2
        targetCPUUtilizationPercentage:
          type: integer
          default: 90
    envs:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          value:
            type: string

ui:
  ui:order:
    - "*"
