apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  {{- range.Values.envs }}
  {{ .name }}: {{ .value | default "" | b64enc }}
  {{- end }}
