apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "application.fullname" . }}
  labels:
    {{- include "application.labels" . | nindent 4 }}
data:
  {{- range.Values.envs }}
  {{ .name }}: {{ .value | default "" | b64enc }}
  {{- end }}
