name: Validate on PR Open
on:
  pull_request:
    types: [opened]

jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Massdriver CLI
        uses: dsaltares/fetch-gh-release-asset@0.0.8
        with:
          repo: "massdriver-cloud/massdriver-cli"
          file: "^mass-.*-linux-amd64\\.tar\\.gz$"
          regex: true

      - name: Build
        env:
          MASSDRIVER_API_KEY: ${{"{{"}} secrets.MASSDRIVER_API_KEY {{"}}"}}
        run: tar -xzf mass-*.tar.gz -C /usr/local/bin && rm -rf mass-*.tar.gz .git* && mass bundle build massdriver.yaml

      - name: Validate params schema
        run: mass schema validate -s https://json-schema.org/draft-07/schema -d ./schema-params.json

      - name: Validate connections schema
        run: mass schema validate -s https://json-schema.org/draft-07/schema -d ./schema-connections.json

      - name: Validate artifacts schema
        run: mass schema validate -s https://json-schema.org/draft-07/schema -d ./schema-artifacts.json

      - name: Terraform validate
        uses: dflook/terraform-validate@v1
        id: validate
        with:
          path: src
